# Importar bibliotecas

In [0]:
import pandas as pd
import matplotlib.pyplot as plt

# Leitura do arquivo fa084_tch_mult.xlsx (Excel) e fa084_tch_mult.csv

In [0]:
# Leitura do xlsx
df_xlsx = pd.read_excel('fa084_tch_mult.xlsx', index_col=0)
df_xlsx.head()

lstd_iii    lstn_iii     lstd_ii     lstn_ii  ...  variedade  solo  espac    tch
0  299.186864  290.494075  306.401096  291.992136  ...   RB867515    LP    1,4  55.55
1  298.088264  288.173150  306.461866  293.165228  ...   RB867515    LP    1,4  48.38
2  298.088264  288.173150  306.461866  293.165228  ...   SP801842    LP    1,4  42.70
3  298.088264  288.173150  306.311575  292.932962  ...   SP801842    LP    1,4  43.41
4  298.105825  288.102431  306.119656  292.990958  ...   RB966928    LP    1,4  43.84

[5 rows x 14 columns]

In [0]:
# Leitura do csv
df = pd.read_csv('fa084_tch_mult.csv')
df.head()

lstd_iii    lstn_iii     lstd_ii     lstn_ii  ...  variedade  solo  espac    tch
0  299.186864  290.494075  306.401096  291.992136  ...   RB867515    LP    1,4  55.55
1  298.088264  288.173150  306.461866  293.165228  ...   RB867515    LP    1,4  48.38
2  298.088264  288.173150  306.461866  293.165228  ...   SP801842    LP    1,4  42.70
3  298.088264  288.173150  306.311575  292.932962  ...   SP801842    LP    1,4  43.41
4  298.105825  288.102431  306.119656  292.990958  ...   RB966928    LP    1,4  43.84

[5 rows x 14 columns]

## Explorar os dados

### Qual a dimensão do conjunto de dados (linhas, colunas)?

In [0]:
df.shape

(13645, 14)

In [0]:
# Nomes das colunas
df.columns

Index(['lstd_iii', 'lstn_iii', 'lstd_ii', 'lstn_ii', 'lstd_i', 'lstn_i',
       'ppt_i', 'ppt_ii', 'ppt_iii', 'estagio', 'variedade', 'solo', 'espac',
       'tch'],
      dtype='object')

In [0]:
# Dados estatísticos
df.describe()

lstd_iii      lstn_iii  ...       estagio           tch
count  13645.000000  13645.000000  ...  13645.000000  13645.000000
mean     301.357332    290.913343  ...      3.103188     63.510379
std        3.023086      1.925815  ...      1.410392     21.180891
min      294.271928    285.097733  ...      1.000000     15.300000
25%      299.283164    289.556563  ...      2.000000     48.330000
50%      300.855256    290.842877  ...      3.000000     61.690000
75%      303.123797    292.290694  ...      4.000000     77.510000
max      311.903862    295.996409  ...      7.000000    127.180000

[8 rows x 11 columns]

In [0]:
# Tipos de dados
df.dtypes

### Qual a média das temperaturas diurnas por fase de crescimento (i, ii e iii)?
### E a média geral?

In [0]:
# Média das temperaturas diurnas por fase de crescimento
# Período i: 
df.lstd_i.mean()

305.23229085978835

In [0]:
# Período ii:
df.lstd_ii.mean()

303.6644324903685

In [0]:
# Período iii:
df.lstd_iii.mean()

301.3573323171336

In [0]:
# Média geral das temperaturas diurnas
(df.lstd_i.sum()+df.lstd_ii.sum()+df.lstd_iii.sum())/(3*df.shape[0])

303.41801855576256

### Qual a média das temperaturas noturnas por fase de crescimento (i, ii e iii)?
### E a média geral?

In [0]:
# Média das temperaturas noturnas por fase de crescimento
# Período i: 


In [0]:
# Período ii: 


In [0]:
# Período iii: 


In [0]:
# Média geral das temperaturas noturnas


### Média de produtividade

In [0]:
# Média geral de produtividade considerando todos os estágios (número de corte) e todas as variedades
df.tch.mean()

63.51037889336768

In [0]:
# Média de produtividade por variedade
df.groupby('variedade').tch.mean().sort_values(ascending=False)

variedade
RB835054    79.738207
RB855453    78.510132
SP803280    78.335440
SP801842    76.506965
RB966928    67.359658
SP835073    66.419509
RB845210    66.407839
RB855536    66.289258
RB867515    61.925565
RB855156    60.098413
others      59.947638
SP832847    58.905116
SP813250    57.511456
RB835486    54.096448
RB72454     50.868354
Name: tch, dtype: float64

In [0]:
# Média de produtividade por estágio de corte
df.groupby('estagio').tch.mean().sort_values(ascending=False)

estagio
1    74.634147
2    68.891431
7    65.049583
3    64.859805
4    56.288605
5    54.629578
6    53.732945
Name: tch, dtype: float64

### Variedades

In [0]:
# Qual a distribuição de talhões por variedades existentes no conjunto de dados?
df.variedade.value_counts()

RB867515    5112
SP813250    2500
RB855453     985
others       851
RB855156     750
RB855536     633
SP832847     561
RB835054     541
SP801842     425
SP835073     326
RB835486     259
RB845210     199
SP803280     193
RB72454      164
RB966928     146
Name: variedade, dtype: int64

In [0]:
# Quantas variedades existem no conjunto de dados?
df.variedade.value_counts().count()

15

In [0]:
# Quais as duas variedades mais frequentes? Em quantos talhões?


In [0]:
# # Quais as duas variedades menos frequentes? Em quantos talhões?


In [0]:
# Número de talhões com as diferentes variedades, por estágio de corte
df.variedade.groupby(df.estagio).value_counts()

estagio  variedade
1        RB867515     731
         SP813250     313
         RB855453     169
         others       166
         RB855536     158
                     ... 
7        RB835486       6
         SP803280       6
         RB855453       4
         SP801842       2
         others         2
Name: variedade, Length: 94, dtype: int64

In [0]:
# Quais as duas variáveis com maior produtividade?
df['tch'].groupby(df['variedade']).mean().sort_values(ascending=False)

### Solos

In [0]:
# Quantos tipos de solos existem? E quantos talhões existem com cada tipo de solo?
df.solo.value_counts()

LP    7265
R     5922
O      458
Name: solo, dtype: int64

### Gráficos (vários)

In [0]:
# Gráfico de barras apresentando a distribuição do número de talhões por variedade
df.variedade.value_counts().plot.bar();

In [0]:
# Gráfico de pontos (scatter) das produtividades por estágio de corte
df.plot.scatter(x='estagio',y='tch')

In [0]:
# Gráfico de barras com o número de talhões com cada tipo de solo
df.solo.value_counts().plot.bar(rot=0);

In [0]:
# Gráfico boxplot da produtividade (todos estágios, todas as variedades, etc.)
df.boxplot(column='tch')

In [0]:
# Gráfico boxplot da produtividade, separado por estágio (todas as variedades)
df.boxplot(column='tch', by='estagio');

# Regressão

## Regressão Linear

In [0]:
# Importar bibliotecas
import numpy as np
from sklearn.linear_model import LinearRegression

In [0]:
# Criar um exemplo com duas variáveis: x e y
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [0]:
# Criar um regressor (lrm: linear regression model)
lrm = LinearRegression()

In [0]:
# Fazer ajuste da curva utilizando o regressor lrm e os vetores x e y
lr_modelo = lrm.fit(x,y)

# ALTERNATIVA
# Fazer tudo em uma única linha
# lr_modelo = LinearRegression().fit(x,y)

In [0]:
# Calcular o coeficiente de determinação do modelo (R quadrado)
r_sq = lr_modelo.score(x,y)
r_sq

In [0]:
# Obter os valores dos coeficientes b0 e b1
b0 = lr_modelo.intercept_  # (valor único)
b1 = lr_modelo.coef_       # (vetor)

In [0]:
b1

In [0]:
# Predições
y_pred = lr_modelo.predict(x)

# OBS: Os valores de y_pred obtidos por este comando necessariamente 
#      devem ser iguais ao obtidos por "lr_modelo.intercept_ + lr_modelo.coef_ * x"

## Regressão Linear Múltipla

In [0]:
# Importar bibliotecas
import numpy as np
from sklearn.linear_model import LinearRegression

In [0]:
# Criar conjuntos de dados: x (matriz) e y
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [0]:
# Criar regressor mlrm (Multiple Linear Regression Model)
mlrm = LinearRegression()

In [0]:
# Fazer ajuste da curva utilizando o regressor mlrm e os vetores x e y
mlr_modelo = mlrm.fit(x,y)

In [5]:
# Calcular o coeficiente de determinação do modelo (R quadrado)
r_sq = mlr_modelo.score(x,y)
r_sq

0.8615939258756776

In [0]:
# Obter os valores dos coeficientes b0, b1 e b2
b0 = mlr_modelo.intercept_
b1b2 = mlr_modelo.coef_

In [7]:
b1b2

array([0.44706965, 0.25502548])

In [0]:
# Predições
y_pred = mlr_modelo.predict(x)

In [9]:
y_pred

array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
       29.4660957 , 38.78227633, 41.27265006])

## Regressão Polinomial

In [0]:
# Importar bibliotecas
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [0]:
# Criar um exemplo com duas variáveis: x e y
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [0]:
# ATENÇÃO!!! NOVO PASSO!!!  NECESSÁRIO PARA REGRESSÃO POLINOMIAL!!!
# Transformar os dados de entrada conforme o grau do polinômio a ser utilizado
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [0]:
# Utilizando o vetor x, fazer o ajuste do tranformador definido anteriormente
transformer.fit(x)

In [0]:
# Criar matriz com valores ajustados com o transformador
x_ = transformer.transform(x)

In [0]:
# ALTERNATIVA
# Fazer tudo em uma única linha
# x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [0]:
# x_ retorna uma matriz com os valores de entrada transformados.
# Neste exemplo, a primeira coluna com os valores originais e a segunda, 
# com os quadrados desses valores
# Imprimir x_
print(x_)

In [0]:
# Fazer ajuste da curva utilizando os vetores x e y
prm = LinearRegression().fit(x_,y)   # prm: Polynomial Regression Model

In [0]:
# Calcular o coeficiente de determinação do modelo (R quadrado)
r_sq = prm.score(x_,y)
r_sq

0.8908516262498564

In [0]:
# Obter os valores dos coeficientes b0, b1 e b2
b0 = prm.intercept_
b1b2 = prm.coef_

In [0]:
b1b2

array([-1.32357143,  0.02839286])

In [0]:
# OBS IMPORTANTE!!! Se incluir bias=True matriz modificada vai incluir 
# intercept = 1 para todos os registros

# Nesse caso, quando for fazer a regressão, fit_intercept deve ser False
# LinearRegression(fit_intercept=False).fit(x_, y)

# No resultado, 'intercept' vai ser 0.0, mas nos coeficientes, vai aparecer
# o primeiro valor como sendo o valor b0 de um modelo y = b0 + b1 x + b2 x^2

In [0]:
# Predições
y_pred = prm.predict(x_)

## Regressão Polinomial Múltipla

In [0]:
# Importar bibliotecas
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [0]:
# Criar um conjunto de dados com matriz x e vetor y
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [0]:
# Criar matriz com valores ajustados com o transformador (tudo em uma única linha)
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [0]:
# Ajustar o modelo utilizando a matriz transformada e o vetor y
model = LinearRegression().fit(x_, y)

In [0]:
# Calcular o coeficiente de determinação do modelo (R quadrado)
r_sq = model.score(x_, y)

In [0]:
# Obter os valores dos coeficientes b(i) - Comando em uma única linha
# OBS: Neste exemplo, vão existir seis coeficientes: 
# b0, b1, b2, b3, b4 e b5
# f(x1,x2) = b0 + b1 x1 + b2 x2 + b3 x1^2 + b4 x1 x2 + b5 x2^2
intercept, coefficients = model.intercept_, model.coef_   

In [0]:
# Predições utilizando a matriz transformada
y_pred = model.predict(x_)

# Métricas de avaliação

## MSE: Mean Squared Error

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=2020)

In [0]:
l_reg = LinearRegression()
l_model = l_reg.fit(X_train, y_train)

In [0]:
y_pred = l_model.predict(x_test)

In [0]:
rmse_l_model = mean_squared_error(y_test, y_pred)